name: AWS OIDC Connect 
on:
  push

env:
  AWS_REGION: eu-west-1

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  OIDC:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::851725178273:role/github-oidc-role
          role-session-name: eksclustersession
          aws-region: ${{ env.AWS_REGION }}

      - name: Print AWS SSM Parameter
        run: aws ssm get-parameter --name=ctse_aws_oidc --query Parameter.Value

      - name: Print assumed role
        run: aws sts get-caller-identity
